ifdef android specific parts of UnityRemoteController.cs
there might be a better way to do this (platform specific assembly) but i've never used those before.

hopefully this will fix this error:

Assets\Scripts\Hammer\UnityRemoteController.cs(3,31): error CS0234: The type or namespace name 'Android' does not exist in the namespace 'UnityEngine.InputSystem' (are you missing an assembly reference?)